# scripts/yazilar/02_tanim_deger_goruntu.py — ikinci blog yazisi (23.09.2026)
# Standart: blog-YAZIM-STANDARDI.md · sayisal iddialar: scripts/blog_dogrula.py
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))
from blog_ogeler import hap, dikkat, ornek, onkosul, sinavda, tablo  # noqa: E402

YAZI = {
    "slug": "tanim-deger-goruntu-kumeleri",
    "baslik": "Tanım, Değer ve Görüntü Kümeleri",
    "aciklama": "Tanım kümesi, değer kümesi ve görüntü kümesi arasındaki fark; en geniş tanım kümesi ve görüntü kümesi bulma yöntemleri, çözümlü örneklerle.",
    "tarih": "2026-09-23",
    "guncelleme": None,
    "kategori": "fonksiyonlar",
    "sinavlar": ["TYT", "AYT"],
    "kapak": "tanim-deger-goruntu-kumeleri",
    "kapak_alt": "Tanım, değer ve görüntü kümeleri: masadaki renkli kartları duvardaki bölmelere yerleştiren iki öğrenci; bölmelerin bir kısmı dolu, bir kısmı boş",
    "ozet": "Fonksiyon sorularının büyük kısmı aslında bir küme sorusudur. Bu fonksiyona hangi değerleri verebilirim, çıkış hangi kümeden seçiliyor, gerçekte hangi değerler çıkıyor? Bu üç sorunun cevabı sırasıyla tanım kümesi, değer kümesi ve görüntü kümesidir. Bu yazıda üçünü ayrı ayrı tanımlıyor, en geniş tanım kümesini ve görüntü kümesini adım adım bulmayı öğreniyor, sık yapılan karışıklıkları tek tek ele alıyoruz.",
    "bolumler": [
        {"baslik": "Üç küme, üç soru", "icerik": [
            onkosul(
                "Bu yazıyı daha rahat anlamak için fonksiyonun tanımını (her girişin tek bir çıkışı olması), aralık gösterimini ve birinci dereceden eşitsizlik çözmeyi biliyor olman yeterli.",
                "Fonksiyon kavramı yeni geliyorsa önce <a href=\"/blog/fonksiyonlar-konu-anlatimi/\">Fonksiyonlar Konu Anlatımı</a> yazısına göz at."),
            "Bir $f:A \\to B$ fonksiyonu yazıldığında aslında üç küme birden konuşulur. Birini ötekiyle karıştırmamanın en kolay yolu, her kümenin hangi soruya cevap verdiğini bilmektir:",
            "<ul><li><strong>Tanım kümesi</strong> $A$: Fonksiyona hangi değerleri verebilirim?</li><li><strong>Değer kümesi</strong> $B$: Çıkış hangi kümenin içinden seçiliyor?</li><li><strong>Görüntü kümesi</strong> $f(A)$: Çıkışta gerçekten hangi değerler ortaya çıkıyor?</li></ul>",
            "Bunu bir yerleştirme oyunu gibi düşünebilirsin. Masada bir kutu kart, duvarda bir raf dolusu bölme var. Kural şu: masadaki <strong>her</strong> kart duvardaki <strong>tek bir</strong> bölmeye konacak. Masadaki kartlar tanım kümesidir. Duvardaki bütün bölmeler değer kümesidir. Oyun bittiğinde içinde en az bir kart olan bölmeler ise görüntü kümesidir.",
            "Bu benzetmeden iki sonuç hemen çıkar. Masada kart kalmaz; tanım kümesinin her elemanı kullanılır. Duvarda ise boş bölme kalabilir ve bir bölmeye birden fazla kart konabilir; değer kümesinin hepsinin kullanılması gerekmez.",
            hap("Tanım kümesinin <strong>hepsi</strong> kullanılır, değer kümesinin hepsi kullanılmak zorunda değildir.",
                "Bu yüzden her zaman $f(A) \\subseteq B$ dir."),
            ornek(
                "$A=\\{-1,0,1,2\\}$, $B=\\{0,1,2,3,4,5\\}$ ve $f(x)=x^2$ olsun.",
                "Tanım, değer ve görüntü kümelerini yazalım.",
                "Tanım kümesi verilen $A$ kümesidir: $\\{-1,0,1,2\\}$.",
                "Değer kümesi verilen $B$ kümesidir: $\\{0,1,2,3,4,5\\}$.",
                "Görüntüleri tek tek hesaplayalım: $f(-1)=1$, $f(0)=0$, $f(1)=1$, $f(2)=4$.",
                "Görüntü kümesi $\\{0,1,4\\}$ tür. $1$ iki kez çıktı ama kümede bir kez yazılır.",
                "$2$, $3$ ve $5$ değer kümesinde olduğu hâlde hiç çıkmadı; bunlar boş kalan bölmelerdir."),
        ]},
        {"baslik": "Tanım kümesi", "icerik": [
            "Tanım kümesi, fonksiyona girdi olarak verilebilecek bütün değerlerin kümesidir. $f:A \\to B$ yazılışında okun solundaki kümedir. Tanım kümesi iki farklı biçimde karşına çıkar:",
            "<ul><li><strong>Açıkça verilir.</strong> $f:\\{1,2,3\\} \\to \\mathbb{R}$ ya da $f:[0,5] \\to \\mathbb{R}$ gibi. Hesaplanacak bir şey yoktur; fonksiyon yalnızca bu değerlerde çalışır.</li>"
            "<li><strong>Verilmez, yalnızca kural yazılır.</strong> $f(x)=\\dfrac{1}{x-2}$ gibi. Bu durumda tanım kümesi olarak kuralın anlamlı olduğu <strong>en geniş</strong> gerçel sayı kümesi alınır. Buna <strong>en geniş tanım kümesi</strong> denir.</li></ul>",
            "Tanım kümesi fonksiyonun bir parçasıdır, sonradan eklenen bir ayrıntı değildir. Aynı kural farklı tanım kümeleriyle yazıldığında ortaya farklı fonksiyonlar çıkar.",
            ornek(
                "$f:\\mathbb{R} \\to \\mathbb{R}$, $f(x)=x^2$ ve $g:[0,3] \\to \\mathbb{R}$, $g(x)=x^2$ olsun.",
                "Bu iki fonksiyon aynı mıdır?",
                "Kuralları aynı görünüyor, ama $f$ her gerçel sayıda çalışırken $g$ yalnızca $0$ ile $3$ arasında çalışır.",
                "Örneğin $f(-2)=4$ tanımlıdır. $g(-2)$ ise tanımsızdır, çünkü $-2$ sayısı $g$ nin tanım kümesinde yoktur.",
                "Görüntü kümeleri de farklıdır: $f$ ninki $[0,\\infty)$, $g$ ninki $[0,9]$ dur.",
                "Tanım kümeleri farklı olduğu için bu iki fonksiyon eşit değildir."),
            dikkat(
                "Tanım kümesi verilmişse onu sen genişletemezsin.",
                "$f:[0,3] \\to \\mathbb{R}$ yazıldıysa kural $x=5$ için hesaplanabiliyor olsa bile $f(5)$ tanımsızdır."),
        ]},
        {"baslik": "En geniş tanım kümesi nasıl bulunur?", "icerik": [
            "Kural verilip tanım kümesi verilmediğinde soru şudur: hangi gerçel sayılar bu ifadeyi <strong>tanımsız</strong> yapar? Bunları $\\mathbb{R}$ den çıkarırsın, kalan küme en geniş tanım kümesidir.",
            "Gerçel sayılarda bir ifadeyi tanımsız yapan durumlar azdır ve hepsi aşağıdaki tabloda:",
            tablo(["İfade", "Şart"], [
                ["Polinom: $3x^2-x+5$", "Şart yok"],
                ["Kesir: $\\dfrac{P(x)}{Q(x)}$", "$Q(x) \\neq 0$"],
                ["Çift dereceden kök: $\\sqrt{P(x)}$", "$P(x) \\geq 0$"],
                ["Paydada çift kök: $\\dfrac{1}{\\sqrt{P(x)}}$", "$P(x) > 0$"],
                ["Tek dereceden kök: $\\sqrt[3]{P(x)}$", "Kökten gelen şart yok"],
                ["Logaritma: $\\log_{a} P(x)$", "$P(x)>0$, $a>0$, $a \\neq 1$"],
            ]),
            "Tabloda \"şart yok\" yazan satırlar yalnızca o yapının kendisinden bir şart gelmediğini söyler. İçerideki ifadenin kendi şartı varsa o da aranır. Örneğin $\\sqrt[3]{\\dfrac{1}{x}}$ ifadesinde küp kök şart koymaz, ama içerideki kesir $x \\neq 0$ ister.",
            hap("En geniş tanım kümesi için her yapının şartını <strong>ayrı ayrı</strong> yaz, sonra hepsinin <strong>kesişimini</strong> al.",
                "Payda sıfır olamaz, çift kökün içi negatif olamaz, logaritmanın içi pozitif olmalıdır."),
            ornek(
                "$f(x)=\\dfrac{2x+1}{x^2-9}$ olsun.",
                "En geniş tanım kümesini bulalım.",
                "Pay bir polinomdur; şart koymaz.",
                "Payda sıfır olamaz: $x^2-9 \\neq 0$, yani $x \\neq 3$ ve $x \\neq -3$.",
                "En geniş tanım kümesi $\\mathbb{R}-\\{-3,3\\}$ tür."),
            ornek(
                "$f(x)=\\sqrt{6-2x}+\\dfrac{1}{x+1}$ olsun.",
                "En geniş tanım kümesini bulalım.",
                "Kök içi negatif olamaz: $6-2x \\geq 0 \\Rightarrow x \\leq 3$.",
                "Payda sıfır olamaz: $x \\neq -1$.",
                "İki şartın kesişimi: $(-\\infty,-1) \\cup (-1,3]$."),
        ]},
        {"baslik": "Kök ve kesir bir aradaysa", "icerik": [
            "Kök paydadaysa iki şart üst üste biner: kök içi negatif olamaz, kökün değeri de sıfır olamaz. İkisi birlikte kök içinin <strong>kesinlikle pozitif</strong> olmasını ister. Örneğin $\\dfrac{5}{\\sqrt{x+4}}$ için $x+4>0$, yani $x>-4$ olmalıdır. Tanım kümesi $(-4,\\infty)$ dur.",
            "Kökün içinde çarpanlarına ayrılabilen bir ifade varsa, işaretini sayı doğrusu üzerinde incelemek en güvenli yoldur. Buna <strong>işaret tablosu</strong> denir: ifadeyi sıfır yapan değerler sayı doğrusuna yazılır ve her aralıkta ifadenin işareti belirlenir.",
            ornek(
                "$f(x)=\\sqrt{x^2-5x+6}$ olsun.",
                "En geniş tanım kümesini bulalım.",
                "Kök içi negatif olamaz: $x^2-5x+6 \\geq 0$.",
                "Çarpanlarına ayıralım: $x^2-5x+6=(x-2)(x-3)$. Bu ifade $x=2$ ve $x=3$ te sıfır olur.",
                "$x<2$ için iki çarpan da negatiftir, $x>3$ için ikisi de pozitiftir; iki durumda da çarpım pozitiftir. $2<x<3$ için ise çarpım negatiftir.",
                "Kontrol: $x=2.5$ için çarpım $(0.5) \\cdot (-0.5)=-0.25$ olur ve negatiftir.",
                "Tanım kümesi $(-\\infty,2] \\cup [3,\\infty)$ dur."),
            ornek(
                "$f(x)=\\sqrt{\\dfrac{x-1}{x+3}}$ olsun.",
                "En geniş tanım kümesini bulalım.",
                "Kök içi negatif olamaz: $\\dfrac{x-1}{x+3} \\geq 0$. Ayrıca payda sıfır olamaz: $x \\neq -3$.",
                "Pay $x=1$ de, payda $x=-3$ te sıfır olur. $x<-3$ için pay da payda da negatiftir ve oran pozitiftir. $-3<x<1$ için oran negatiftir. $x>1$ için oran pozitiftir.",
                "Oranı sıfır yapan $x=1$ dahil edilir, paydayı sıfır yapan $x=-3$ dahil edilmez.",
                "Tanım kümesi $(-\\infty,-3) \\cup [1,\\infty)$ dur."),
            dikkat(
                "$\\sqrt{x^2}$ ile $(\\sqrt{x})^2$ aynı tanım kümesine sahip değildir.",
                "$\\sqrt{x^2}=|x|$ her gerçel sayıda tanımlıdır. $(\\sqrt{x})^2$ ise yalnızca $x \\geq 0$ için tanımlıdır.",
                "Tanım kümesini ifadeyi sadeleştirmeden <strong>önce</strong> bul; sadeleştirme başlangıçtaki tanım kümesini değiştirmez."),
        ]},
        {"baslik": "Logaritmalı ve üslü ifadeler", "icerik": [
            "Logaritmayı henüz görmediysen bu bölümü atlayıp sonra dönebilirsin.",
            "$\\log_{a} b$ ifadesinin tanımlı olması için üç şart vardır: $b>0$, $a>0$ ve $a \\neq 1$. Taban da içerik de $x$ e bağlıysa üçü birden yazılır ve kesişim alınır.",
            ornek(
                "$f(x)=\\log_{x-1}(5-x)$ olsun.",
                "En geniş tanım kümesini bulalım.",
                "İçerik pozitif olmalı: $5-x>0 \\Rightarrow x<5$.",
                "Taban pozitif olmalı: $x-1>0 \\Rightarrow x>1$.",
                "Taban $1$ olamaz: $x-1 \\neq 1 \\Rightarrow x \\neq 2$.",
                "Üç şartın kesişimi: $(1,2) \\cup (2,5)$."),
            "Tabanı sabit ve pozitif olan $2^x$, $3^{x+1}$ gibi üslü ifadeler her gerçel $x$ için tanımlıdır. Şart üslü yapıdan değil, üsteki ifadenin kendisinden gelir. Örneğin $2^{\\frac{1}{x}}$ ifadesinde $x \\neq 0$ şartı üsteki kesirden gelir.",
        ]},
        {"baslik": "f(ax+b) türü sorularda tanım kümesi", "icerik": [
            "Tanım kümesiyle ilgili klasik bir soru tipi şudur: $f$ nin tanım kümesi verilir, $f(2x-1)$ ifadesinin tanım kümesi sorulur. Ya da tam tersi.",
            "Buradaki kilit fikir şu: $f$ nin tanım kümesi, $f$ ye <strong>verilen</strong> değerlerin kümesidir. $f(2x-1)$ yazıldığında $f$ ye verilen değer $x$ değil, $2x-1$ dir. Dolayısıyla şart $x$ e değil, parantezin içine konur.",
            hap("$f$ nin tanım kümesi, $f$ nin <strong>parantezinin içine</strong> yazılan ifadenin alabileceği değerlerdir.",
                "$f(2x-1)$ in tanım kümesi sorulduğunda $2x-1$ bu kümeye sokulur ve $x$ çözülür."),
            ornek(
                "$f$ nin tanım kümesi $[1,7]$ olsun.",
                "$f(2x-1)$ in tanım kümesini bulalım.",
                "Parantezin içi $f$ nin tanım kümesinde olmalı: $1 \\leq 2x-1 \\leq 7$.",
                "Her tarafa $1$ ekleyelim: $2 \\leq 2x \\leq 8$.",
                "Her tarafı $2$ ye bölelim: $1 \\leq x \\leq 4$.",
                "$f(2x-1)$ in tanım kümesi $[1,4]$ tür.",
                "Kontrol: $x=1$ için $2x-1=1$, $x=4$ için $2x-1=7$. İki uç da $f$ nin tanım kümesine düşüyor."),
            ornek(
                "$f(3-x)$ in tanım kümesi $[0,5]$ olsun.",
                "$f$ nin tanım kümesini bulalım.",
                "Bu kez $x$ in aralığı verilmiş; parantezin içinin alabileceği değerleri bulacağız.",
                "$0 \\leq x \\leq 5$ ise her tarafı $-1$ ile çarpalım; eşitsizlik yön değiştirir: $-5 \\leq -x \\leq 0$.",
                "Her tarafa $3$ ekleyelim: $-2 \\leq 3-x \\leq 3$.",
                "$f$ nin tanım kümesi $[-2,3]$ tür."),
        ]},
        {"baslik": "Birden fazla f içeren ifadeler", "icerik": [
            "Bir ifadede $f$ birden fazla kez geçiyorsa her $f$ nin parantezi ayrı ayrı tanım kümesine sokulur ve çıkan aralıkların kesişimi alınır. İfadenin hesaplanabilmesi için her parçanın aynı anda tanımlı olması gerekir.",
            ornek(
                "$f$ nin tanım kümesi $[0,5]$ olsun.",
                "$f(x+3)+f(1-x)$ ifadesinin tanım kümesini bulalım.",
                "Birinci parça: $0 \\leq x+3 \\leq 5 \\Rightarrow -3 \\leq x \\leq 2$.",
                "İkinci parça: $0 \\leq 1-x \\leq 5 \\Rightarrow -4 \\leq x \\leq 1$.",
                "İki aralığın kesişimi: $[-3,1]$."),
            "Parantezin içinde doğrusal olmayan bir ifade de olabilir. $f$ nin tanım kümesi $[-2,6]$ ise $f(x^2)$ için $-2 \\leq x^2 \\leq 6$ olmalıdır. Sol taraf her zaman sağlanır, çünkü bir karenin değeri negatif olamaz. Sağ taraf $x^2 \\leq 6$ verir, yani $-\\sqrt{6} \\leq x \\leq \\sqrt{6}$. Tanım kümesi $[-\\sqrt{6},\\sqrt{6}]$ dır.",
            dikkat(
                "$f(2x-1)$ ifadesindeki $x$ ile $f$ nin kendi girdisi aynı şey değildir.",
                "Soru \"$f(2x-1)$ in tanım kümesi\" diyorsa cevap $x$ in aralığıdır. \"$f$ nin tanım kümesi\" diyorsa cevap parantez içinin aralığıdır.",
                "Önce hangisinin sorulduğunu yaz, sonra işleme geç."),
        ]},
        {"baslik": "Değer kümesi", "icerik": [
            "Değer kümesi, fonksiyonun çıkışlarının <strong>içinden seçildiği</strong> kümedir. $f:A \\to B$ yazılışında okun sağındaki $B$ kümesidir.",
            "Değer kümesi hesaplanmaz, <strong>verilir</strong>; fonksiyonu tanımlayan kişi onu seçer. Soruda yalnızca kural verilmişse değer kümesi olarak genellikle $\\mathbb{R}$ düşünülür.",
            "Değer kümesinin tek bir zorunluluğu vardır: bütün çıkışları içine alabilmelidir. Bir çıkış değer kümesinin dışına taşıyorsa ortada fonksiyon yoktur.",
            ornek(
                "$A=\\{1,2,3\\}$, $B=\\{2,3\\}$ ve $f(x)=x+1$ kuralı verilsin.",
                "$f:A \\to B$ bir fonksiyon mudur?",
                "$f(1)=2$ ve $f(2)=3$ değerleri $B$ nin içindedir.",
                "$f(3)=4$ ise $B$ de yoktur; $3$ elemanı eşlenecek bir yer bulamaz.",
                "Tanım kümesinde açıkta eleman kaldığı için $f:A \\to B$ bir fonksiyon <strong>değildir</strong>.",
                "Değer kümesi olarak $\\{2,3,4\\}$ ya da onu içeren daha büyük bir küme seçilseydi fonksiyon olurdu."),
            "Benzer bir durum tanım kümesi seçerken de ortaya çıkar. $f(x)=\\sqrt{x}$ kuralı $f:\\mathbb{R} \\to \\mathbb{R}$ biçiminde yazılamaz, çünkü $-1$ in gidebileceği bir gerçel sayı yoktur. Doğru yazılış $f:[0,\\infty) \\to \\mathbb{R}$ dir.",
            hap("Değer kümesi <strong>verilir</strong>, görüntü kümesi <strong>hesaplanır</strong>.",
                "Değer kümesinin tek şartı bütün çıkışları kapsamasıdır."),
            "Değer kümesi ilk bakışta gereksiz bir ayrıntı gibi görünebilir, ama örtenlik tamamen ona bağlıdır. Görüntü kümesi değer kümesine eşitse fonksiyon <strong>örten</strong>, değilse <strong>içine</strong> fonksiyondur. Aynı $f(x)=x^2$ kuralı $\\mathbb{R} \\to \\mathbb{R}$ olarak örten değildir, $\\mathbb{R} \\to [0,\\infty)$ olarak örtendir. Kural değişmedi, yalnızca değer kümesi değişti.",
        ]},
        {"baslik": "Görüntü kümesi", "icerik": [
            "Görüntü kümesi, tanım kümesindeki bütün elemanların görüntülerinden oluşan kümedir:",
            "$$f(A)=\\{f(x) : x \\in A\\}$$",
            "Sözle söylersek: tanım kümesindeki her elemanı fonksiyona ver, çıkan sonuçları topla. Tekrar eden sonuçlar bir kez yazılır.",
            "Tanım kümesi sonlu ve küçükse görüntü kümesini bulmanın en güvenli yolu her elemanın görüntüsünü tek tek hesaplamaktır. Tanım kümesi bir aralıksa ya da $\\mathbb{R}$ ise tek tek hesap mümkün değildir; o zaman fonksiyonun davranışına bakılır. Sonraki bölümler bu davranışları fonksiyon türlerine göre ele alıyor.",
            ornek(
                "$A=\\{-2,-1,0,1,2\\}$ ve $f(x)=x^2+1$ olsun.",
                "$f(A)$ yı bulalım.",
                "$f(-2)=5$, $f(-1)=2$, $f(0)=1$, $f(1)=2$, $f(2)=5$.",
                "Tekrar edenleri bir kez yazarız: $f(A)=\\{1,2,5\\}$.",
                "Tanım kümesinde $5$ eleman vardı, görüntü kümesinde $3$ eleman kaldı. Çünkü $-1$ ile $1$, $-2$ ile $2$ aynı görüntüye gitti."),
            hap("Sonlu kümelerde görüntü kümesinin eleman sayısı tanım kümesininkini geçemez: $s(f(A)) \\leq s(A)$.",
                "Eşitlik yalnızca fonksiyon birebirse olur."),
            sinavda(
                "Temel düzeyde (<strong>TYT</strong>) soru sonlu kümelerle kurulabilir: bir liste ya da şema verilir, görüntü kümesi ya da onun eleman sayısı istenir. Paydalı ve köklü ifadelerin en geniş tanım kümesi de bu düzeyde sorulabilir.",
                "İleri düzeyde (<strong>AYT</strong>) aralıklar devreye girer: $f(2x-1)$ türü kaydırma soruları, parabolün bir aralıktaki görüntü kümesi, kesirli fonksiyonun görüntü kümesi ve logaritmalı ifadelerin tanım kümesi bu düzeydedir."),
        ]},
        {"baslik": "Doğrusal fonksiyonun görüntü kümesi", "icerik": [
            "$f(x)=ax+b$ biçimindeki doğrusal bir fonksiyon ($a \\neq 0$), $a>0$ ise artan, $a<0$ ise azalan bir fonksiyondur. Artan ya da azalan bir fonksiyonun bir aralıktaki en küçük ve en büyük değeri aralığın uçlarında ortaya çıkar. Bu yüzden görüntü kümesi için uçları yerine koymak yeterlidir.",
            ornek(
                "$f(x)=3x-2$ ve tanım kümesi $[-1,4]$ olsun.",
                "Görüntü kümesini bulalım.",
                "$a=3>0$ olduğu için fonksiyon artandır; en küçük değer sol uçta, en büyük değer sağ uçtadır.",
                "$f(-1)=-5$ ve $f(4)=10$.",
                "Görüntü kümesi $[-5,10]$ dur."),
            ornek(
                "$f(x)=5-2x$ ve tanım kümesi $[0,3)$ olsun.",
                "Görüntü kümesini bulalım.",
                "$a=-2<0$ olduğu için fonksiyon azalandır: $x$ büyüdükçe $f(x)$ küçülür.",
                "$f(0)=5$ ve bu değer alınır, çünkü $0$ tanım kümesindedir.",
                "$f(3)=-1$ ama $3$ tanım kümesinde olmadığı için $-1$ değeri alınmaz.",
                "Görüntü kümesi $(-1,5]$ tir."),
            dikkat(
                "Azalan fonksiyonda uçlar yer değiştirir.",
                "Tanım kümesinin <strong>sol</strong> ucu görüntü kümesinin <strong>sağ</strong> ucunu verir. Açık ve kapalı uçlar da onlarla birlikte taşınır."),
        ]},
        {"baslik": "İkinci dereceden fonksiyonun görüntü kümesi", "icerik": [
            "$f(x)=ax^2+bx+c$ fonksiyonu ($a \\neq 0$) doğrusal fonksiyon gibi tek yönlü değildir. Grafiği bir paraboldür: $a>0$ ise önce azalır sonra artar, $a<0$ ise önce artar sonra azalır. Yön değiştirdiği noktaya <strong>tepe noktası</strong> denir. Tepe noktasının apsisi, yani $x$ koordinatı, $x=-\\dfrac{b}{2a}$ dir.",
            "Tanım kümesi $\\mathbb{R}$ ise görüntü kümesi tepe noktasındaki değerle belirlenir. Bu değere $k$ dersek, $a>0$ için görüntü kümesi $[k,\\infty)$, $a<0$ için $(-\\infty,k]$ olur.",
            hap("$a>0$ ise parabolün en küçük değeri, $a<0$ ise en büyük değeri tepe noktasındadır.",
                "Tepe noktasının apsisi $x=-\\dfrac{b}{2a}$ dir."),
            ornek(
                "$f(x)=x^2-4x+7$ ve tanım kümesi $\\mathbb{R}$ olsun.",
                "Görüntü kümesini bulalım.",
                "Tepe noktasının apsisi: $x=-\\dfrac{-4}{2 \\cdot 1}=2$.",
                "Tepe değeri: $f(2)=4-8+7=3$.",
                "$a=1>0$ olduğu için $3$ en küçük değerdir ve fonksiyon yukarı doğru sınırsız büyür.",
                "Görüntü kümesi $[3,\\infty)$ dur.",
                "Aynı sonuca tam kareye tamamlayarak da ulaşılır: $x^2-4x+7=(x-2)^2+3$. Bir kare en az $0$ olduğu için ifade en az $3$ tür."),
        ]},
        {"baslik": "Parabolde tanım kümesi bir aralıksa", "icerik": [
            "Tanım kümesi bir aralıkla sınırlandırılmışsa uçları yerine koymak <strong>yetmez</strong>. Tepe noktası aralığın içindeyse en küçük (ya da en büyük) değer orada çıkar ve uçlar bunu göstermez.",
            hap("Kapalı bir aralıkta parabolün en küçük ve en büyük değerleri <strong>tepe noktası</strong> ile <strong>iki uç</strong> arasından çıkar.",
                "Tepe aralığın dışındaysa yalnızca uçlara bakmak yeter."),
            ornek(
                "$f(x)=x^2-4x+7$ ve tanım kümesi $[0,5]$ olsun.",
                "Görüntü kümesini bulalım.",
                "Tepe noktasının apsisi $x=2$ ve bu değer $[0,5]$ aralığının içinde. En küçük değer $f(2)=3$ tür.",
                "Uçlara bakalım: $f(0)=7$ ve $f(5)=25-20+7=12$.",
                "En büyük değer uçlardan büyük olanıdır: $12$.",
                "Görüntü kümesi $[3,12]$ dir."),
            dikkat(
                "Yalnızca uçları yerine koysaydık $[7,12]$ bulurduk ve bu yanlıştır; $f(2)=3$ değeri o aralıkta yoktur.",
                "Parabolde önce tepe noktasının aralığın içinde olup olmadığına bak."),
            "Tepe noktası aralığın dışındaysa fonksiyon o aralıkta tek yönlüdür ve uçlar yeter. Örneğin aynı fonksiyon $[3,6]$ aralığında artandır. $f(3)=4$ ve $f(6)=19$ olduğundan görüntü kümesi $[4,19]$ dur.",
        ]},
        {"baslik": "Kesirli fonksiyonun görüntü kümesi", "icerik": [
            "$f(x)=\\dfrac{2x+1}{x-3}$ gibi bir fonksiyonda görüntü kümesini bulmak için şu soruyu sorarız: hangi $y$ değerleri için $f(x)=y$ denkleminin tanım kümesinde bir çözümü vardır? Denklemi $x$ için çözeriz; çözümün olmadığı $y$ değerleri görüntü kümesinin dışında kalır.",
            ornek(
                "$f(x)=\\dfrac{2x+1}{x-3}$ olsun.",
                "Görüntü kümesini bulalım.",
                "$y=\\dfrac{2x+1}{x-3}$ yazıp paydayı karşıya atalım: $y(x-3)=2x+1$.",
                "Dağıtalım: $yx-3y=2x+1$.",
                "$x$ li terimleri bir tarafta toplayalım: $yx-2x=3y+1$, yani $x(y-2)=3y+1$.",
                "$y \\neq 2$ ise $x=\\dfrac{3y+1}{y-2}$ bulunur.",
                "Bu $x$ hiçbir zaman $3$ olmaz: $3y+1=3y-6$ eşitliği imkânsızdır. Yani her $y \\neq 2$ için tanım kümesinde bir çözüm vardır.",
                "$y=2$ ise denklem $0=7$ olur; çözüm yoktur.",
                "Görüntü kümesi $\\mathbb{R}-\\{2\\}$ dir."),
            "Bu yöntemin kısa bir sonucu vardır ve sınavda zaman kazandırır.",
            hap("$f(x)=\\dfrac{ax+b}{cx+d}$ ise ($c \\neq 0$ ve $ad-bc \\neq 0$):",
                "Tanım kümesi $\\mathbb{R}-\\{-\\dfrac{d}{c}\\}$, görüntü kümesi $\\mathbb{R}-\\{\\dfrac{a}{c}\\}$ dır."),
            dikkat(
                "$ad-bc=0$ ise bu kısayol çalışmaz, çünkü fonksiyon aslında sabittir.",
                "Örneğin $f(x)=\\dfrac{2x+4}{x+2}$ için $ad-bc=2 \\cdot 2-4 \\cdot 1=0$ dır.",
                "Sadeleştirince $x \\neq -2$ için $f(x)=2$ bulunur. Görüntü kümesi $\\mathbb{R}-\\{2\\}$ değil, yalnızca $\\{2\\}$ dir."),
        ]},
        {"baslik": "Köklü, mutlak değerli ve üslü fonksiyonlar", "icerik": [
            "Bu fonksiyonlarda görüntü kümesini bulmanın ortak yolu, ifadenin <strong>en küçük parçasından</strong> başlayıp eşitsizliği adım adım kurmaktır. Kullanacağımız üç temel gerçek şunlar:",
            "<ul><li>$\\sqrt{u}$ ifadesi $0$ ı ve bütün pozitif değerleri alabilir, negatif değer almaz.</li>"
            "<li>$|u|$ ifadesi de $0$ ı ve bütün pozitif değerleri alabilir, negatif değer almaz.</li>"
            "<li>$a>0$ ve $a \\neq 1$ ise $a^u$ her zaman pozitiftir. $u$ bütün gerçel sayıları dolaşırken $a^u$ bütün pozitif değerleri alır.</li></ul>",
            ornek(
                "$f(x)=\\sqrt{x-1}+2$ olsun.",
                "Görüntü kümesini bulalım.",
                "Tanım kümesi: $x-1 \\geq 0$, yani $x \\geq 1$.",
                "$x$ bu aralıkta dolaşırken $\\sqrt{x-1}$ ifadesi $0$ dan başlayarak bütün negatif olmayan değerleri alır.",
                "Her tarafa $2$ ekleyelim: $f(x) \\geq 2$.",
                "Görüntü kümesi $[2,\\infty)$ dur."),
            ornek(
                "$f(x)=3-|x+2|$ olsun.",
                "Görüntü kümesini bulalım.",
                "$|x+2| \\geq 0$ dır ve $x=-2$ için $0$ olur.",
                "Eksiyle çarpınca yön değişir: $-|x+2| \\leq 0$.",
                "Her tarafa $3$ ekleyelim: $f(x) \\leq 3$.",
                "$|x+2|$ bütün negatif olmayan değerleri aldığı için $f(x)$ de $3$ ü ve altındaki bütün değerleri alır. Görüntü kümesi $(-\\infty,3]$ tür."),
            hap("Görüntü kümesi bulurken ifadenin en küçük parçasından başla ve eşitsizliği adım adım kur.",
                "Negatif bir sayıyla çarparken eşitsizliğin yönünü çevir."),
            "Aynı yol üslü ifadelerde de işler. $f(x)=2^x+1$ için $2^x>0$ olduğundan $f(x)>1$ dir ve görüntü kümesi $(1,\\infty)$ dur. Burada $1$ değeri <strong>hiçbir zaman</strong> alınmaz, çünkü $2^x$ sıfıra yaklaşır ama sıfır olmaz.",
            "İki sınırın birden olduğu bir durum: $f(x)=\\sqrt{9-x^2}$ için tanım kümesi $[-3,3]$ tür. Kök içi $9-x^2$ bu aralıkta $0$ ile $9$ arasındaki bütün değerleri alır; kökü alınınca $f(x)$ $0$ ile $3$ arasındaki bütün değerleri alır. Görüntü kümesi $[0,3]$ tür.",
        ]},
        {"baslik": "Görüntü kümesi ve ters fonksiyon", "icerik": [
            "Kesirli fonksiyonda kullandığımız \"$y$ yi yaz, $x$ i çek\" yöntemi, ters fonksiyon bulmanın ilk yarısıdır. Bu bir tesadüf değildir.",
            "Birebir bir $f$ fonksiyonunu tanım kümesinden görüntü kümesine düşünelim; böylece hem birebir hem örten olur. Tersi $f^{-1}$ çıkıştan girişe döner. Dolayısıyla $f^{-1}$ in girdi olarak alabileceği değerler tam olarak $f$ nin çıkışlarıdır.",
            hap("$f$ birebirse $f^{-1}$ in tanım kümesi $f$ nin görüntü kümesidir. $f^{-1}$ in görüntü kümesi de $f$ nin tanım kümesidir.",
                "Görüntü kümesini bulmakta zorlanıyorsan tersin tanım kümesine bak."),
            ornek(
                "$f(x)=\\dfrac{2x+1}{x-3}$ fonksiyonunun tersi $f^{-1}(x)=\\dfrac{3x+1}{x-2}$ dir.",
                "Bu iki fonksiyonun tanım ve görüntü kümelerini karşılaştıralım.",
                "$f$ nin tanım kümesi $\\mathbb{R}-\\{3\\}$, görüntü kümesi $\\mathbb{R}-\\{2\\}$ dir.",
                "$f^{-1}$ in tanım kümesi $\\mathbb{R}-\\{2\\}$, görüntü kümesi $\\mathbb{R}-\\{3\\}$ tür.",
                "İki küme yer değiştirdi."),
        ]},
        {"baslik": "Grafikten tanım ve görüntü kümesi okuma", "icerik": [
            "Grafiği verilen bir fonksiyonda iki küme doğrudan okunur:",
            "<ul><li><strong>Tanım kümesi</strong>, grafiğin soldan sağa kapladığı bütün $x$ değerleridir.</li><li><strong>Görüntü kümesi</strong>, grafiğin aşağıdan yukarıya kapladığı bütün $y$ değerleridir.</li></ul>",
            "Bunu gölge gibi düşünebilirsin. Grafiği yukarıdan aşağıya bastırıp $x$ eksenine yapıştırdığını hayal et; eksende kalan iz tanım kümesidir. Yandan bastırıp $y$ eksenine yapıştırırsan kalan iz görüntü kümesidir. Bu işleme <strong>izdüşüm</strong> denir. Grafiğin uçlarındaki <strong>dolu nokta</strong> o değerin dahil olduğunu, <strong>boş nokta</strong> dahil olmadığını gösterir.",
            hap("Grafikte tanım kümesi $x$ eksenine, görüntü kümesi $y$ eksenine düşen izdüşümdür.",
                "Dolu nokta dahil, boş nokta hariç."),
            ornek(
                "Bir $f$ fonksiyonunun grafiği iki doğru parçasından oluşsun. Birinci parça dolu $(-3,1)$ noktasından başlayıp $(1,5)$ noktasına çıkıyor. İkinci parça $(1,5)$ ten başlayıp boş $(4,-2)$ noktasına iniyor.",
                "Tanım ve görüntü kümesini bulalım.",
                "$x$ değerleri $-3$ ten başlıyor ($-3$ dahil) ve $4$ e kadar gidiyor ($4$ dahil değil). Tanım kümesi $[-3,4)$ tür.",
                "Birinci parça $y$ ekseninde $1$ den $5$ e kadar, yani $[1,5]$ aralığını kaplar.",
                "İkinci parça $5$ ten $-2$ ye iner ve $-2$ dahil değildir. Kapladığı aralık $(-2,5]$ tir.",
                "İkisinin birleşimi görüntü kümesidir: $(-2,5]$."),
            dikkat(
                "Görüntü kümesini grafiğin <strong>uç noktalarından</strong> okumaya çalışma.",
                "Bu örnekte uçların $y$ değerleri $1$ ve $-2$ dir, ama en büyük değer olan $5$ bir uçta değil, ortadaki tepede."),
        ]},
        {"baslik": "Eleman sayısı soruları", "icerik": [
            "Sonlu kümeler arasındaki fonksiyonlarda görüntü kümesi sayma sorularının da konusu olur. Temel sonuç şudur: $s(A)=m$ ve $s(B)=n$ ise $A$ dan $B$ ye $n^m$ fonksiyon vardır. Çünkü $A$ nın her elemanı için $B$ den bağımsız olarak $n$ seçenek vardır.",
            ornek(
                "$A=\\{1,2,3\\}$ ve $B=\\{a,b,c,d\\}$ olsun.",
                "$A$ dan $B$ ye tanımlanan fonksiyonlardan kaçının görüntü kümesi tam olarak iki elemanlıdır?",
                "Önce görüntü kümesine girecek iki elemanı seçelim: $\\binom{4}{2}=6$ yol.",
                "Seçilen iki eleman $\\{a,b\\}$ olsun. $A$ nın üç elemanını bu iki elemana göndermenin $2^3=8$ yolu vardır.",
                "Bunlardan ikisinde bütün elemanlar aynı yere gider ve görüntü kümesi tek elemanlı kalır. Geriye $8-2=6$ yol kalır.",
                "Toplam: $6 \\cdot 6=36$ fonksiyon."),
            "Sonucu kontrol etmenin güzel bir yolu var. Görüntü kümesi $1$, $2$ ya da $3$ elemanlı olabilir. Tek elemanlı olanlar sabit fonksiyonlardır: $4$ tane. Üç elemanlı olanlar birebir fonksiyonlardır: $4 \\cdot 3 \\cdot 2=24$ tane. İki elemanlılar $36$ tane. Toplam $4+36+24=64$ eder ve bu da $4^3$ e eşittir.",
            "Bir elemanın görüntüsü sabitlenirse o eleman seçimden çıkar. Aynı kümelerle $f(1)=a$ koşulunu sağlayan fonksiyon sayısı $4^2=16$ dır: $1$ in yeri belli, kalan iki elemanın her biri için $4$ seçenek vardır.",
            hap("Görüntü kümesi <strong>tam olarak</strong> belli bir küme olan fonksiyonları sayarken, o kümeye giden bütün fonksiyonlardan kümenin bir kısmını boş bırakanları çıkar.",
                "İki elemanlı bir hedef küme için bu sayı $2^m-2$ dir."),
        ]},
        {"baslik": "Sık yapılan hatalar", "icerik": [
            tablo(["Hata", "Doğrusu"], [
                ["Görüntü kümesini değer kümesiyle bir tutmak", "$f(A) \\subseteq B$; eşit olmak zorunda değil"],
                ["Kök içine $>0$ yazmak", "Çift kökte $\\geq 0$; kök paydadaysa $>0$"],
                ["Önce sadeleştirip sonra tanım kümesi bulmak", "Önce tanım kümesi, sonra sadeleştirme"],
                ["$f(2x-1)$ sorusunda şartı $x$ e koymak", "Şart parantezin içine konur"],
                ["Parabolde yalnızca uçları yerine koymak", "Tepe aralıktaysa uç değer orada da çıkar"],
                ["Azalan fonksiyonda uçları sırasıyla yazmak", "Sol uç sağa geçer"],
                ["$\\dfrac{ax+b}{cx+d}$ kısayolunu her zaman kullanmak", "$ad-bc=0$ ise fonksiyon sabittir"],
                ["Tekrar eden görüntüyü iki kez saymak", "Kümede her eleman bir kez yazılır"],
            ]),
            "Bu hataların çoğu aynı yerden çıkar: soruda hangi kümenin istendiğine bakmadan işleme geçmek. Başlamadan önce kâğıda \"tanım mı, değer mi, görüntü mü?\" diye yazmak birçoğunu baştan keser.",
        ]},
    ],
    "sss": [
        ("Tanım kümesi ile değer kümesi arasındaki fark nedir?",
         "Tanım kümesi fonksiyona verilebilecek girdilerin kümesidir. Değer kümesi ise çıkışların içinden seçildiği kümedir. Tanım kümesinin her elemanı kullanılır; değer kümesinde hiç kullanılmayan elemanlar kalabilir."),
        ("Görüntü kümesi değer kümesine eşit olabilir mi?",
         "Evet. Görüntü kümesi değer kümesine eşitse fonksiyona örten fonksiyon denir. Değer kümesinde hiç kullanılmayan eleman varsa fonksiyon içine fonksiyondur."),
        ("En geniş tanım kümesi nasıl bulunur?",
         "İfadeyi tanımsız yapan değerler çıkarılır. Payda sıfır olamaz, çift dereceden kökün içi negatif olamaz, logaritmanın içi pozitif, tabanı da pozitif ve birden farklı olmalıdır. Her şart ayrı ayrı yazılır ve kesişimleri alınır."),
        ("Görüntü kümesi nasıl bulunur?",
         "Tanım kümesi sonluysa her elemanın görüntüsü tek tek hesaplanır. Aralıkta tanımlı fonksiyonlarda fonksiyonun davranışına bakılır: doğrusal fonksiyonda uçlar, parabolde tepe noktası ve uçlar, kesirli fonksiyonda ise y yi yazıp x i çekme yöntemi kullanılır."),
        ("f(2x−1) ifadesinin tanım kümesi nasıl bulunur?",
         "Parantezin içindeki 2x−1 ifadesi, f nin tanım kümesindeki değerleri almalıdır. Bu şart eşitsizlik olarak yazılır ve x çözülür. Çıkan x aralığı, f(2x−1) ifadesinin tanım kümesidir."),
        ("Değer kümesi hesaplanabilir mi?",
         "Hayır. Değer kümesi fonksiyonu tanımlayan kişi tarafından seçilir ve verilir. Hesaplanan küme görüntü kümesidir. Soruda yalnızca kural verilmişse değer kümesi olarak genellikle gerçel sayılar kümesi düşünülür."),
    ],
    "kontrol": [
        "Bir fonksiyonda tanım, değer ve görüntü kümesini ayrı ayrı gösterebiliyorum.",
        "Sonlu bir tanım kümesinde görüntü kümesini tek tek hesaplayıp tekrar edenleri bir kez yazıyorum.",
        "Paydalı, köklü ve logaritmalı bir ifadenin en geniş tanım kümesini şartların kesişimiyle bulabiliyorum.",
        "Kök paydadayken $\\geq$ yerine $>$ yazmam gerektiğini biliyorum.",
        "İşaret tablosuyla $\\sqrt{(x-a)(x-b)}$ türü ifadelerin tanım kümesini bulabiliyorum.",
        "$f$ nin tanım kümesinden $f(2x-1)$ inkini, $f(2x-1)$ inkinden de $f$ ninkini bulabiliyorum.",
        "Azalan bir doğrusal fonksiyonda görüntü kümesinin uçlarını doğru yerleştiriyorum.",
        "Parabolün bir aralıktaki görüntü kümesini bulurken tepe noktasını kontrol ediyorum.",
        "$\\dfrac{ax+b}{cx+d}$ türü bir fonksiyonun görüntü kümesini bulabiliyor, $ad-bc=0$ durumunu ayırt ediyorum.",
        "Bir grafikten tanım ve görüntü kümesini, dolu ve boş noktalara dikkat ederek okuyabiliyorum.",
    ],
    "kaynaklar": [
        ("MEB Ortaöğretim Matematik Dersi Öğretim Programı", "https://mufredat.meb.gov.tr/ProgramDetay.aspx?PID=343"),
    ],
    "ilgili": ["fonksiyonlar-konu-anlatimi", "birebir-orten-fonksiyon", "ters-fonksiyon"],
}
