server {
  listen 80;
  root /var/www/html;
  index index.php index.html;

  # Traefik /blog prefixini sildiði için burada WP kökten çalýþýr
  location / { try_files $uri $uri/ /index.php?$args; }

  location ~ \.php$ {
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_pass wp-fpm:9000;
  }

  location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|webp)$ {
    expires max;
    access_log off;
  }
}
